### ISSUE TITLE
Possible DSS endpoints inconsistency 

### ISSUE THREAD

**Issue by arrcher** [astm-utm/Protocol#16]
Hello,
I have noticed that the query endpoint for constraints of DSS interface is not aligned with other endpoints. It's 
`POST /dss/v1/constraints/query`
but 
`GET /dss/v1/constraint_references/{entityuuid}`
`PUT /dss/v1/constraint_references/{entityuuid}`
`DELETE /dss/v1/constraint_references/{entityuuid}`

Is it done deliberately to resolve ambiguity between `query` and `{entity uuid}` or it's something that needs to be adjusted?

If it's the first option then `/dss/v1/operation_references/` endpoint needs to be revised as well.

--
Best regards,
Alexei

**Comment by BenjaminPelletier** [comment]
If `POST /dss/v1/constraints/query` had a `{entityuuid}` path parameter, what would the client populate that parameter with?  That endpoint is a request to list all Constraint references in the DSS that intersect with a specified area/volume/time; it wouldn't make sense to specify a specific Constraint ID as a parameter to that search request.

**Comment by arrcher** [comment]
Sorry that I was not clear. 
I see inconsistency between `/dss/v1/constraints/` and `/dss/v1/constraint_references/` endpoints.
For operation entities, all four endpoints have same base resource path `/dss/v1/operation_references/...` .

**Comment by BenjaminPelletier** [comment]
Ah yes, thanks for the clarification as I didn't understand properly the first time.  I'll see about making a PR for this.
