### ISSUE TITLE
DSS API GeoJSON Polygon Discrepancy

### ISSUE THREAD

**Issue by jfisherge** [astm-utm/Protocol#17]
The current version of the API (0.3.1) defines the [coordinates member of a Polygon](https://github.com/astm-utm/Protocol/blob/9cd8b3496f06b6f5ba5f776ec29bc8aff5b4de43/utm.yaml#L341) as an array of [Points](https://tools.ietf.org/html/rfc7946#section-3.1.2). This look like the following (forgiving the duplicate points):
```
{
    "type": "Polygon",
    "coordinates": [
      [
        {
          "type": "Point",
          "coordinates": [
            -122.106325,
            47.660898
          ]
        },
        {
          "type": "Point",
          "coordinates": [
            -122.106325,
            47.660898
          ]
        },
        {
          "type": "Point",
          "coordinates": [
            -122.106325,
            47.660898
          ]
        },
        {
          "type": "Point",
          "coordinates": [
            -122.106325,
            47.660898
          ]
        }
      ]
    ]
}
```

The GeoJSON spec says the format for the coordinates member a [Polygon](https://tools.ietf.org/html/rfc7946#section-3.1.6) should be a [LineString](https://tools.ietf.org/html/rfc7946#section-3.1.4), which is an array of two or more [Positions](https://tools.ietf.org/html/rfc7946#section-3.1.1). An example of a `Polygon` would be:
```
{
    "type": "Polygon",
    "coordinates": [
      [
        [
            -122.106325,
            47.660898
        ],
        [
            -122.106325,
            47.660898
        ],
        [
            -122.106325,
            47.660898
        ],
        [
            -122.106325,
            47.660898
        ]
      ]
    ]
}
```

We should follow the GeoJSON spec for interoperability reasons. This will help with quicker implementation for those USSs that use standard GeoJSON libraries.

**Comment by astm-utm** [comment]
You're correct-- the Polygon object was referencing the wrong vertex schema. This is fixed in version 0.3.3.
