### ISSUE TITLE
Object deletion needs versioning

### ISSUE THREAD

**Issue by BenjaminPelletier** [astm-utm/Protocol#20]
Currently, DELETE Subscriptions, Operations, and Constraints all lack an indication of the version the client is intending to delete.  This leads to the following problem:

1. Client creates Sub1 with ID1
2. Client queues a deletion job for Sub1 on their system
3. Client's deletion job encounters a 5xx error on the first DSS instance to which it tries to issue the DELETE Subscription command
4. Client creates Sub2 with ID1
5. Client's deletion job retries the DELETE Subscription command on a second DSS instance and it succeeds
6. Client is expecting Sub2 to exist when actually is has been deleted

This type of problem is avoided by having the client tell the DSS which version of the object it is intended to operate on -- in the case of creation and updates, we have `old_version` which provides this information.  However, request parameters should not be provided with RESTful DELETE operations, so we can't/shouldn't follow that approach for DELETE.  The best solution would probably be to follow the remote ID API and include the version in the path.  So, for instance, we would have these endpoints:

* PUT `~/subscriptions/{subscriptionid}` (create new Subscription)
* GET `~/subscriptions/{subscriptionid}` (get existing Subscription)
* PUT `~/subscriptions/{subscriptionid}/{version}` (update existing Subscription)
* DELETE `~/subscriptions/{subscriptionid}/{version}` (delete existing Subscription)

Note that, like remote ID, the DSS would not keep multiple versions at any given time; the version in the path merely serves to ensure that commands are executed in the intended order to avoid issues like the one detailed above.

**Comment by arrcher** [comment]
Could it be possible that DELETE and PUT for constraints and operations have similar issue?

**Comment by BenjaminPelletier** [comment]
Yes, currently, DELETE Subscriptions, Operations, and Constraints all lack an indication of the version the client is intending to delete.  PUT does not have the issue because of the `old_version` parameter.  DELETE is unique because it does not allow parameters when following standard practices.

**Comment by BenjaminPelletier** [comment]
Group discussion: this API change is ok, but we will discuss requirement for UUID in standard itself which may make this issue unnecessary.
